site_name: Pretzel Documentation
theme:
  name: material
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant.prefetch
    - navigation.tabs
    - toc.integrate
    - navigation.top
    - toc.follow
    - navigation.sections
    - content.tabs.link
    - content.code.copy
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
plugins:
  - search
  - redirects:
      redirect_maps:
        aggdocs.md: AGG-User-group-documentation/Finding-a-marker-or-gene-on-a-genome.md